language:
- objective-c
env:
  global:
  - BUILD_COMMIT=latest-tag  # comment out to build version in submodule
  - REPO_DIR=nipy
  - NIPY_WHEEL_URL=https://nipy.bic.berkeley.edu/scipy_installers
  matrix:
  - VERSION=2.7.10 NUMPY_VERSION=1.6.2 # tune to taste
  - VERSION=3.3.5 NUMPY_VERSION=1.7.1
  - VERSION=3.4.3 NUMPY_VERSION=1.7.1
  - VERSION=3.5.0 NUMPY_VERSION=1.7.1
install:
  - source terryfy/travis_tools.sh
  # Enforce clang to avoid excessive compile warnings on Python 3.5
  - export CC=clang
  - export CXX=clang++
  - get_python_environment macpython $VERSION venv
  # Update to latest wheel package for Python 3.5
  - pip install -U wheel
  - pip install delocate
  - pip install -f $NIPY_WHEEL_URL numpy==$NUMPY_VERSION scipy nibabel sympy cython
  - if [ -n "$BUILD_COMMIT" ]; then
        checkout_commit $REPO_DIR $BUILD_COMMIT;
    fi
  # Copy Python 3 patched setup_egg.py into distribution
  - cp patches/setup_egg.py nipy
  # Build, install wheel
  - cd nipy
  - python setup_egg.py bdist_wheel
  - delocate-listdeps dist/*.whl # lists library dependencies
  - delocate-wheel dist/*.whl # copies library dependencies into wheel
  - delocate-addplat --rm-orig -x 10_9 -x 10_10 dist/*.whl
  - pip install dist/*.whl
  - cd ..
script:
  # install dependencies for tests e.g - pip install nose
  # Fix numpy ast errors in tests by upgrading numpy
  - if [ -n "$(pyver_ge $VERSION 3.4.0)" ]; then
        pip install --upgrade numpy;
    fi
  - pip install nose
  - mkdir tmp_for_test
  - cd tmp_for_test
  # Run the tests
  - python ../$REPO_DIR/tools/nipnost nipy
  - cd ..
before_deploy:
  - cd $REPO_DIR/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: "kx7GzRZXAfm3kRdciRDl3mp0L3gHpowgCTsy8YSOWoyv3TIl+5uqljKAyxCKtBKNhBADQDYY9lgkxTtyeTwot2BWWFBIgrHRxqootksYRX2xY9shjnT9eGCaO7sifWcGzYIdFQl5DJruWh2UnpAhqoAUR35NlVqSJWp1jl79To9G9SRNyUN+d0NzV03v/460gXYPj01smclVYknDQiqrosoJ1At6eybzpO5qGqYHk4FoHPtb26AjSCymDMSw07EEUsaWbAo0zzG0TjDnFtMyMk9DaAj3C9V8OTqXy0YWs614XiLgBl8clQU4stK3DmkttY5gV9ck6rhiMRpGWDLXaNLazPl5LhB7CDh9L1WSbIXvXNx2jPse4ci+cmL5xt2dyrCNkkmGU01aJRBHYFU1h03wjNOZpelbj2VFD2w0SppF5A+FalBPUo9bprwk0sqqfRHD+S9jF5ZGljZIoU7ERoGppPMFKd6PEbLaP/2+nqfH8ZJralB3SKmCB5kgKKVElHuBVr4cYQokyrlMTYWZoWyTPche2q4nXDpBZJWL11NHr7GH+hcVWtWpv2U/wSgvt71/8FbeFKN+fPwEtv6FMWT9RMLmGeuqfxU59xWw7o/mNDd6f0aQo6fhqma6ZN2cxidBYP4XBFRBGPPYmV1R1Jnrf63SbRKSdYql14il1Xc="
  region: ORD
  container: wheels
  skip_cleanup: true
