environment:
  global:
    REPO_DIR: nipy
    PACKAGE_NAME: nipy
    BUILD_COMMIT: 0.4.1
    NP_BUILD_DEPENDS: "numpy==1.7.1"
    NP_TEST_DEPENDS: "numpy==1.7.1"
    WHEELHOUSE_UPLOADER_USERNAME: travis-worker
    WHEELHOUSE_UPLOADER_SECRET:
        secure:
            9s0gdDGnNnTt7hvyNpn0/ZzOMGPdwPp2SewFTfGzYk7uI+rdAN9rFq2D1gAP4NQh

    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C %APPVEYOR_BUILD_FOLDER%\\multibuild\\ci\\appveyor\\windows_sdk.cmd"

  matrix:
    - PYTHON: "C:\\Miniconda"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Miniconda3"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      NP_BUILD_DEPENDS: "numpy==1.9.3"
      NP_TEST_DEPENDS: "numpy==1.9.3"
    - PYTHON: "C:\\Miniconda3-x64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      NP_BUILD_DEPENDS: "numpy==1.9.3"
      NP_TEST_DEPENDS: "numpy==1.9.3"
    - PYTHON: "C:\\Miniconda35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      NP_BUILD_DEPENDS: "numpy==1.9.3"
      NP_TEST_DEPENDS: "numpy==1.9.3"
    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      NP_BUILD_DEPENDS: "numpy==1.9.3"
      NP_TEST_DEPENDS: "numpy==1.9.3"
    - PYTHON: "C:\\Miniconda36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      NP_BUILD_DEPENDS: "numpy==1.11.3"
      NP_TEST_DEPENDS: "numpy==1.11.3"
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      NP_BUILD_DEPENDS: "numpy==1.11.3"
      NP_TEST_DEPENDS: "numpy==1.11.3"

# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

matrix:
    fast_finish: true

install:
    # Fetch submodules
    - git submodule update --init --recursive

    # Install miniconda
    - ps: .\\multibuild\\ci\\appveyor\\install.ps1
    - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PYTHON%\Library\bin;%PATH%
    - conda info

    # Check that we have the expected version and architecture for Python
    - python --version
    - python -c "import struct; print(struct.calcsize('P') * 8)"

build_script:
    # Install build requirements
    - conda install --yes cython %NP_BUILD_DEPENDS%

    # build wheel:
    - cd %REPO_DIR%
    - git checkout %BUILD_COMMIT%
    - "%CMD_IN_ENV% python setup.py bdist_wheel"

test_script:
    # create test env
    - conda create --yes -n test_env python=%PYTHON_VERSION% %NP_TEST_DEPENDS% scipy sympy nose mock
    - activate test_env
    - pip install nibabel

    # install from wheel
    - pip install --no-index --find-links dist/ %PACKAGE_NAME%

    # run test from installed wheel.
    - cd ..
    # The tests try to run cython/msvc so CMD_IN_ENV is needed
    - "%CMD_IN_ENV% python -c \"import nipy; nipy.test()\""

artifacts:
    - path: "%REPO_DIR%\\dist\\*"

on_success:
  # Upload the generated wheel package to Rackspace
  # On Windows, Apache Libcloud cannot find a standard CA cert bundle so we
  # disable the ssl checks.
  - pip install wheelhouse-uploader
  - "python -m wheelhouse_uploader upload
    --no-ssl-check --local-folder=%REPO_DIR%\\dist --no-update-index wheels"
